gUniqueModelStatus = {
	-1, -- player
	-1, -- DEFAULTPED
	-1, -- DOgirl_Zoe_EG
	1,  -- NDGirl_Beatrice
	1,  -- NDH1a_Algernon
	1,  -- NDH1_Fatty
	1,  -- ND2nd_Melvin
	1,  -- NDH2_Thad
	1,  -- NDH3_Bucky
	1,  -- NDH2a_Cornelius
	-1, -- NDLead_Earnest
	1,  -- NDH3a_Donald
	1,  -- JKH1_Damon
	1,  -- JKH1a_Kirby
	1,  -- JKGirl_Mandy
	1,  -- JKH2_Dan
	1,  -- JKH2a_Luis
	1,  -- JKH3_Casey
	1,  -- JKH3a_Bo
	-1, -- JKlead_Ted
	1,  -- JK2nd_Juri
	1,  -- GR2nd_Peanut
	1,  -- GRH2A_Hal
	-1, -- GRlead_Johnny
	1,  -- GRH1_Lefty
	1,  -- GRGirl_Lola
	1,  -- GRH3_Lucky
	1,  -- GRH1a_Vance
	1,  -- GRH3a_Ricky
	1,  -- GRH2_Norton
	1,  -- PRH1_Gord
	1,  -- PRH1a_Tad
	1,  -- PRH2a_Chad
	1,  -- PR2nd_Bif
	1,  -- PRH3_Justin
	1,  -- PRH2_Bryce
	-1, -- PRH2_Bryce_OBOX
	-1, -- PRlead_Darby
	1,  -- PRGirl_Pinky
	1,  -- GN_Asiangirl
	1,  -- PRH3a_Parker
	1,  -- DOH2_Jerry
	1,  -- DOH1a_Otto
	1,  -- DOH2a_Leon
	1,  -- DOH1_Duncan
	1,  -- DOH3_Henry
	1,  -- DOH3a_Gurney
	1,  -- DO2nd_Omar
	-1, -- DOGirl_Zoe
	1,  -- PF2nd_Max
	1,  -- PFH1_Seth
	1,  -- PFH2_Edward
	1,  -- PFlead_Karl
	-1, -- TO_Orderly
	1,  -- TE_HallMonitor
	1,  -- TE_GymTeacher
	-1, -- TE_Janitor
	1,  -- TE_English
	-1, -- TE_Cafeteria
	-1, -- TE_Secretary
	1,  -- TE_Nurse
	1,  -- TE_MathTeacher
	1,  -- TE_Librarian
	1,  -- TE_Art
	1,  -- TE_Biology
	-1, -- TE_Principal
	1,  -- GN_Littleblkboy
	1,  -- GN_SexyGirl
	1,  -- GN_Littleblkgirl
	1,  -- GN_Hispanicboy
	1,  -- GN_Greekboy
	1,  -- GN_Fatboy
	1,  -- GN_Boy01
	1,  -- GN_Boy02
	1,  -- GN_Fatgirl
	-1, -- DOlead_Russell
	2,  -- TO_Business1
	2,  -- TO_Business2
	2,  -- TO_BusinessW1
	2,  -- TO_BusinessW2
	2,  -- TO_RichW1
	2,  -- TO_RichW2
	-1, -- TO_Fireman
	1,  -- TO_Cop
	-1, -- TO_Comic
	1,  -- GN_Bully03
	-1, -- TO_Bikeowner
	-1, -- TO_Hobo
	-1, -- Player_Mascot
	-1, -- TO_GroceryOwner
	-1, -- GN_Sexygirl_UW
	-1, -- DOLead_Edgar
	-1, -- JK_LuisWrestle
	-1, -- JKGirl_MandyUW
	-1, -- PRGirl_PinkyUW
	-1, -- NDGirl_BeatriceUW
	-1, -- GRGirl_LolaUW
	1,  -- TO_Cop2
	-1, -- Player_OWres
	1,  -- GN_Bully02
	2,  -- TO_RichM1
	2,  -- TO_RichM2
	1,  -- GN_Bully01
	-1, -- TO_FireOwner
	-1, -- TO_CSOwner_2
	-1, -- TO_CSOwner_3
	1,  -- TE_Chemistry
	1,  -- TO_Poorwoman
	2,  -- TO_MotelOwner
	-1, -- JKKirby_FB
	-1, -- JKTed_FB
	-1, -- JKDan_FB
	-1, -- JKDamon_FB
	-1, -- TO_Carny02
	-1, -- TO_Carny01
	-1, -- TO_CarnyMidget
	2,  -- TO_Poorman2
	-1, -- PRH2A_Chad_OBOX
	-1, -- PRH3_Justin_OBOX
	-1, -- PRH3a_Parker_OBOX
	-1, -- TO_BarberRich
	-1, -- GenericWrestler
	-1, -- ND_FattyWrestle
	-1, -- TO_Industrial
	-1, -- TO_Associate
	-1, -- TO_Asylumpatient
	-1, -- TE_Autoshop
	-1, -- TO_Mailman
	1,  -- TO_Tattooist
	-1, -- TE_Assylum
	-1, -- Nemesis_Gary
	2,  -- TO_Oldman2
	-1, -- TO_BarberPoor
	-1, -- PR2nd_Bif_OBOX
	-1, -- Peter
	2,  -- TO_RichM3
	-1, -- Rat_Ped
	1,  -- GN_LittleGirl_2
	1,  -- GN_LittleGirl_3
	1,  -- GN_WhiteBoy
	-1, -- TO_FMidget
	-1, -- Dog_Pitbull
	1,  -- GN_SkinnyBboy
	-1, -- TO_Carnie_female
	2,  -- TO_Business3
	1,  -- GN_Bully04
	1,  -- GN_Bully05
	1,  -- GN_Bully06
	2,  -- TO_Business4
	2,  -- TO_Business5
	-1, -- DO_Otto_asylum
	1,  -- TE_History
	-1, -- TO_Record
	-1, -- DO_Leon_Assylum
	-1, -- DO_Henry_Assylum
	-1, -- NDH1_FattyChocolate
	-1, -- TO_GroceryClerk
	2,  -- TO_Handy
	-1, -- TO_Orderly2
	-1, -- GN_Hboy_Ween
	-1, -- Nemesis_Ween
	-1, -- GRH3_Lucky_Ween
	-1, -- NDH3a_Donald_ween
	-1, -- PRH3a_Parker_Ween
	-1, -- JKH3_Casey_Ween
	-1, -- Peter_Ween
	-1, -- GN_AsianGirl_Ween
	-1, -- PRGirl_Pinky_Ween
	-1, -- JKH1_Damon_ween
	-1, -- GN_WhiteBoy_Ween
	-1, -- GN_Bully01_Ween
	-1, -- GN_Boy02_Ween
	-1, -- PR2nd_Bif_OBOX_D1
	-1, -- GRH1a_Vance_Ween
	-1, -- NDH2_Thad_Ween
	-1, -- PRGirl_Pinky_BW
	-1, -- DOlead_Russell_BU
	-1, -- PRH1a_Tad_BW
	-1, -- PRH2_Bryce_BW
	-1, -- PRH3_Justin_BW
	-1, -- GN_Asiangirl_CH
	-1, -- GN_Sexygirl_CH
	-1, -- PRGirl_Pinky_CH
	-1, -- TO_NH_Res_01
	-1, -- TO_NH_Res_02
	-1, -- TO_NH_Res_03
	-1, -- NDH1_Fatty_DM
	-1, -- TO_PunkBarber
	-1, -- FightingMidget_01
	-1, -- FightingMidget_02
	-1, -- TO_Skeletonman
	-1, -- TO_Beardedwoman
	-1, -- TO_CarnieMermaid
	-1, -- TO_Siamesetwin2
	-1, -- TO_Paintedman
	-1, -- TO_GN_Workman
	-1, -- DOLead_Edgar_GS
	-1, -- DOH3a_Gurney_GS
	-1, -- DOH2_Jerry_GS
	-1, -- DOH2a_Leon_GS
	-1, -- GRH2a_Hal_GS
	-1, -- GRH2_Norton_GS
	-1, -- GR2nd_Peanut_GS
	-1, -- GRH1a_Vance_GS
	-1, -- JKH3a_Bo_GS
	-1, -- JKH1_Damon_GS
	-1, -- JK2nd_Juri_GS
	-1, -- JKH1a_Kirby_GS
	-1, -- NDH1a_Algernon_GS
	-1, -- NDH3_Bucky_GS
	-1, -- NDH2_Thad_GS
	-1, -- PRH3a_Parker_GS
	-1, -- PRH3_Justin_GS
	-1, -- PRH1a_Tad_GS
	-1, -- PRH1_Gord_GS
	-1, -- NDLead_Earnest_EG
	-1, -- JKlead_Ted_EG
	-1, -- GRlead_Johnny_EG
	-1, -- PRlead_Darby_EG
	-1, -- Dog_Pitbull2
	-1, -- Dog_Pitbull3
	-1, -- TE_CafeMU_W
	-1, -- TO_Millworker
	-1, -- TO_Dockworker
	-1, -- NDH2_Thad_PJ
	-1, -- GN_Lblkboy_PJ
	-1, -- GN_Hboy_PJ
	-1, -- GN_Boy01_PJ
	-1, -- GN_Boy02_PJ
	-1, -- TE_Gym_Incog
	-1, -- JK_Mandy_Towel
	-1, -- JK_Bo_FB
	-1, -- JK_Casey_FB
	-1, -- PunchBag
	0,  -- TO_Cop3
	-1, -- GN_GreekboyUW
	-1, -- TO_Construct01
	-1, -- TO_Construct02
	1,  -- TO_Cop4
	-1, -- PRH2_Bryce_OBOX_D1
	-1, -- PRH2_Bryce_OBOX_D2
	-1, -- PRH2A_Chad_OBOX_D1
	-1, -- PRH2A_Chad_OBOX_D2
	-1, -- PR2nd_Bif_OBOX_D2
	-1, -- PRH3_Justin_OBOX_D1
	-1, -- PRH3_Justin_OBOX_D2
	-1, -- PRH3a_Prkr_OBOX_D1
	-1, -- PRH3a_Prkr_OBOX_D2
	-1, -- TE_Geography
	-1, -- TE_Music
	-1, -- TO_ElfF
	-1, -- TO_ElfM
	-1, -- TO_HoboSanta
	-1, -- TO_Santa
	-1, -- TO_Santa_NB
	-1, -- Peter_Nutcrack
	-1, -- GN_Fatgirl_Fairy
	-1, -- GN_Lgirl_2_Flower
	-1, -- GN_Hboy_Flower
}
